version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: course-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:data/db
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb

volumes:
  mongo_data:

# Bat database: docker-compose up -d
# Tat database: docker-compose down
# Quan ly: http://localhost:8081
# Xem container dang chay: docker ps
# Xem log: docker logs course-mongo
# Truy cap vao shell cua mongo trong container: docker exec -it course-mongo mongosh
# mongoose.connect('mongodb://127.0.0.1:27017/UniversityDB');